export enum LEDConnectionType {
  SERPENTINE_HORIZONTAL_LEFT_RIGHT,
  SERPENTINE_HORIZONTAL_RIGHT_LEFT,
  SERPENTINE_VERTICAL_LEFT_RIGHT,
  SERPENTINE_VERTICAL_RIGHT_LEFT,
  ZIGZAG_HORIZONTAL_LEFT_RIGHT,
  ZIGZAG_HORIZONTAL_RIGHT_LEFT,
  ZIGZAG_VERTICAL_LEFT_RIGHT,
  ZIGZAG_VERTICAL_RIGHT_LEFT
}
